name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: orlasjournal-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk